### ISSUE TITLE
Navigation icons load in different order after page refresh

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-toolbox#4]
With toolbox enabled and PLP the order of the header navigation items changes on page refresh.

Also if start control is enabled in course.json they are ordered differently (like second image below)

![screen shot 2016-10-06 at 10 27 00](https://cloud.githubusercontent.com/assets/6452430/19147392/d7ab0f2c-8baf-11e6-907b-9dee487c3dc9.png)

![screen shot 2016-10-06 at 10 27 09](https://cloud.githubusercontent.com/assets/6452430/19147428/061abf88-8bb0-11e6-895d-48266529608b.png)

**Comment by RobertPeek** [comment]
Cannot replicate. May have been fixed from updates to the framework.
